GIT_SHA := `git rev-parse HEAD`
IMAGE_DOMAIN := "ghcr.io/fpco/cosmos-images"

# List all recipies
default:
	just --list --unsorted

# Build image
build:
	./build-image.sh

# Push image
push-image:
	docker push {{IMAGE_DOMAIN}}:{{GIT_SHA}}
